Repository codestates-seb/seb42_main_011, pull requests merged in 2023-03, with the labels that each got.

#19 [추가] BulletinPost CRUD (2023.03.10 정다운)
  backend/src/main/java/com/mybuddy/bulletin_post/controller/BulletinPostController.java
  backend/src/main/java/com/mybuddy/bulletin_post/dto/BulletinPostDto.java
  backend/src/main/java/com/mybuddy/bulletin_post/entity/BulletinPost.java
  backend/src/main/java/com/mybuddy/bulletin_post/mapper/BulletinPostMapper.java
  backend/src/main/java/com/mybuddy/bulletin_post/repository/BulletinPostRepository.java
  backend/src/main/java/com/mybuddy/bulletin_post/service/BulletinPostService.java
Labels: 개발

#33 [추가] Amentiy전체로직 , BulletinPost와 매핑, BulletinPost Create 상황에 반영
  backend/src/main/java/com/mybuddy/amenity/controller/AmenityController.java
  backend/src/main/java/com/mybuddy/amenity/dto/AmenityCreateDto.java
  backend/src/main/java/com/mybuddy/amenity/dto/AmenityResponseDto.java
  backend/src/main/java/com/mybuddy/amenity/dto/AmenityWithBulletinPost.java
  backend/src/main/java/com/mybuddy/amenity/entity/Amenity.java
  backend/src/main/java/com/mybuddy/amenity/mapper/AmenityMapper.java
  backend/src/main/java/com/mybuddy/amenity/repository/AmenityCustomRepository.java
  backend/src/main/java/com/mybuddy/amenity/repository/AmenityCustomRepositoryImpl.java
  backend/src/main/java/com/mybuddy/amenity/repository/AmenityRepository.java
  backend/src/main/java/com/mybuddy/amenity/service/AmenityService.java
  backend/src/main/java/com/mybuddy/bulletin_post/controller/BulletinPostController.java
  backend/src/main/java/com/mybuddy/bulletin_post/dto/BulletinPostDto.java
  backend/src/main/java/com/mybuddy/bulletin_post/entity/BulletinPost.java
  backend/src/main/java/com/mybuddy/bulletin_post/service/BulletinPostService.java
Labels: 개발

#34 [버그] Amentiy-BulletinPost 매핑 실수 해결 (1:N)
  backend/src/main/java/com/mybuddy/amenity/entity/Amenity.java
  backend/src/main/java/com/mybuddy/bulletin_post/service/BulletinPostService.java
Labels: 버그

#39 [추가] 일반 버튼, 헤더 버튼 컴포넌트 생성 (2023.03.10 왕지호)
  frontend/src/components/UI/Button.js
  frontend/src/components/UI/HeaderButton.js
Labels: 문서

#45 [추가] 특정 장소와 태그된 게시글들 페이지네이션 처리해 반환
  backend/src/main/java/com/mybuddy/amenity/controller/AmenityController.java
  backend/src/main/java/com/mybuddy/amenity/dto/AmenityWithBulletinPost.java
  backend/src/main/java/com/mybuddy/amenity/mapper/AmenityMapper.java
  backend/src/main/java/com/mybuddy/amenity/repository/AmenityCustomRepository.java
  backend/src/main/java/com/mybuddy/amenity/repository/AmenityCustomRepositoryImpl.java
  backend/src/main/java/com/mybuddy/amenity/service/AmenityService.java
  backend/src/main/java/com/mybuddy/bulletin_post/controller/BulletinPostController.java
  backend/src/main/java/com/mybuddy/comment/controller/CommentController.java
  backend/src/main/java/com/mybuddy/comment/mapper/CommentMapper.java
Labels: 개발, 제안

#44 [추가] card 컴포넌트 개발
  frontend/src/components/UI/Card/Card.jsx
Labels: 개발

#47 [수정] button, input 컴포넌트 수정
  frontend/src/components/UI/Button.js
  frontend/src/components/UI/HeaderButton.js
  frontend/src/components/UI/Input.js
Labels: 개발

#51 [버그] bean 생성 오류 해결, 사용되지 않는 mapper 제거
  backend/src/main/java/com/mybuddy/amenity/repository/AmenityCustomRepositoryImpl.java
Labels: 버그

#52 [추가] 모달 컴포넌트 생성
  frontend/public/icon/arrow-right.svg
  frontend/public/icon/close.svg
  frontend/public/icon/comment.svg
  frontend/src/components/UI/Feed/PostItem.jsx
  frontend/src/components/UI/Feed/ProfileItem.jsx
  frontend/src/components/UI/Modal.jsx
Labels: 개발

#54 [추가] Router 적용, 페이지들 추가, button/input js-> jsx 수정
  frontend/public/images/logo.svg
  frontend/src/App.js
  frontend/src/Router.js
  frontend/src/components/Layout/Footer.jsx
  frontend/src/components/Layout/Header.jsx
  frontend/src/components/Layout/Layout.js
  frontend/src/components/Pages/ErrorPage.js
  frontend/src/components/Pages/HomePage.js
  frontend/src/components/Pages/LoginPage.js
  frontend/src/components/Pages/SignupPage.js
  frontend/src/components/UI/Button.jsx
  frontend/src/components/UI/Input.jsx
  frontend/src/index.js
Labels: 개발

#56 [수정/추가] BulletinPost repository 수정, CustomRepository,Impl 추가, global CustomBeanUtils 추가 (2023.03…
  backend/src/main/java/com/mybuddy/amenity/mapper/AmenityMapper.java
  backend/src/main/java/com/mybuddy/bulletin_post/controller/BulletinPostController.java
  backend/src/main/java/com/mybuddy/bulletin_post/repository/BulletinPostCustomRepository.java
  backend/src/main/java/com/mybuddy/bulletin_post/repository/BulletinPostCustomRepositoryImpl.java
  backend/src/main/java/com/mybuddy/bulletin_post/repository/BulletinPostRepository.java
  backend/src/main/java/com/mybuddy/global/utils/CustomBeanUtils.java
Labels: 개발

#58 [추가] CommentControllerTest (Create,Update,Delete)
  backend/src/main/java/com/mybuddy/comment/controller/CommentController.java
  backend/src/main/java/com/mybuddy/comment/dto/CommentCreateDto.java
  backend/src/main/java/com/mybuddy/comment/dto/CommentUpdateDto.java
  backend/src/main/java/com/mybuddy/comment/entity/Comment.java
  backend/src/test/java/com/mybuddy/comment/controller/CommentControllerTest.java
  backend/src/test/java/com/mybuddy/global/mockdata/MockTestData.java
Labels: 테스트

#64 [수정] bulletinPost dto 주석 해제 (2023.03.13 정다운)
  backend/src/main/java/com/mybuddy/bulletin_post/dto/BulletinPostDto.java
Labels: 개발

#67 [리팩토링/버그] Amenity Mapper에 존재하는 중복 메서드 제거, Member null 임시 해결
  backend/src/main/java/com/mybuddy/amenity/mapper/AmenityMapper.java
  backend/src/main/java/com/mybuddy/bulletin_post/controller/BulletinPostController.java
  backend/src/main/java/com/mybuddy/bulletin_post/dto/BulletinPostDto.java
  backend/src/main/java/com/mybuddy/bulletin_post/service/BulletinPostService.java
Labels: 버그, 개발

#69 [수정] CommentResponseDto에 commentId 필드 추가
  backend/src/main/java/com/mybuddy/bulletin_post/mapper/BulletinPostMapper.java
  backend/src/main/java/com/mybuddy/comment/controller/CommentController.java
  backend/src/main/java/com/mybuddy/comment/dto/CommentResponseDto.java
  backend/src/main/java/com/mybuddy/comment/mapper/CommentMapper.java
  backend/src/test/java/com/mybuddy/global/mockdata/MockTestData.java
Labels: 개발

#89 [수정] comment findByBulletinPostId 적용
  backend/src/main/java/com/mybuddy/comment/repository/CommentCustomRepository.java
  backend/src/main/java/com/mybuddy/comment/repository/CommentCustomRepositoryImpl.java
  backend/src/main/java/com/mybuddy/comment/service/CommentService.java
Labels: 개발

#95 [수정/추가] Feed profileItem 수정, 친구 검색창 추가 (2023.03.16 정정수)
  frontend/src/components/Feeds/Feed/ProfileItem.jsx
  frontend/src/components/Feeds/Feeds.jsx
  frontend/src/components/Feeds/FeedsTitle.jsx
  frontend/src/components/UI/Dropdown/DropdownFriend.jsx
  frontend/src/components/UI/SearchInput/SearchInput.jsx
  frontend/src/hooks/useDropdown.js
  frontend/src/hooks/useInputs.js
Labels: 버그, 개발

#97 [추가/버그] search icon 추가, dropdown 초기값 오류 수정(2023.03.16 정정수)
  frontend/src/assets/icons/icon-search.svg
  frontend/src/components/Feeds/FRIEND_DUMY.js
  frontend/src/components/UI/Dropdown/DropdownGender.jsx
Labels: 버그, 개발

#91 [수정/기타] 게시글 상세보기에서 댓글 최신순 (desc) 반환, id전략 변경
  backend/src/main/java/com/mybuddy/amenity/entity/Amenity.java
  backend/src/main/java/com/mybuddy/bulletin_post/mapper/BulletinPostMapper.java
  backend/src/main/java/com/mybuddy/comment/entity/Comment.java
Labels: 개발

#99 [추가/수정] 친추찾기 화면 개발, 홈(피드) 타이틀 오타 수정 ( 2023.03.16 정정수 )
  frontend/src/Pages/FriendSearchPage.jsx
  frontend/src/Pages/HomePage.jsx
  frontend/src/Router.js
  frontend/src/components/Feeds/FeedsTitle.jsx
Labels: 개발

#102 [추가] modal 컴포넌트 portal 적용 및 context 생성 (2023..03.16 정정수)
  frontend/src/App.js
  frontend/src/components/UI/Modal.jsx
  frontend/src/components/UI/Modal/Modal.jsx
  frontend/src/components/UI/Modal/ModalPortal.jsx
  frontend/src/components/UI/Modal/ModalProvider.jsx
  frontend/src/context/ModalContext.jsx
Labels: 개발

#105 [수정] like 추가에 따른 bulletinPost 수정 (2023.03.16 정다운)
  backend/src/main/java/com/mybuddy/bulletin_post/controller/BulletinPostController.java
  backend/src/main/java/com/mybuddy/bulletin_post/entity/BulletinPost.java
  backend/src/main/java/com/mybuddy/bulletin_post/mapper/BulletinPostMapper.java
  backend/src/main/java/com/mybuddy/bulletin_post/service/BulletinPostService.java
  backend/src/main/java/com/mybuddy/like/dto/LikeResponseDto.java
  backend/src/main/java/com/mybuddy/like/entity/Like.java
  backend/src/main/java/com/mybuddy/like/mapper/LikeMapper.java
  backend/src/main/java/com/mybuddy/like/repository/LikeCustomRepository.java
  backend/src/main/java/com/mybuddy/like/repository/LikeCustomRepositoryImpl.java
  backend/src/main/java/com/mybuddy/like/repository/LikeRepository.java
  backend/src/main/java/com/mybuddy/like/service/LikeService.java
Labels: 개발

#111 [추가] AmenityService 슬라이스 테스트
  backend/src/main/java/com/mybuddy/amenity/controller/AmenityController.java
  backend/src/main/java/com/mybuddy/amenity/service/AmenityService.java
  backend/src/main/java/com/mybuddy/bulletin_post/entity/BulletinPost.java
  backend/src/test/java/com/mybuddy/amenity/controller/AmenityControllerTest.java
  backend/src/test/java/com/mybuddy/amenity/service/AmenityServiceTest.java
  backend/src/test/java/com/mybuddy/global/mockdata/MockTestData.java
Labels: 테스트

#116 [추가, 수정] search 추가, bulletin과 like 수정, dto 리팩토링 (2023.03.18 정다운)
  backend/src/main/java/com/mybuddy/bulletin_post/controller/BulletinPostController.java
  backend/src/main/java/com/mybuddy/bulletin_post/dto/BulletinPostDto.java
  backend/src/main/java/com/mybuddy/bulletin_post/mapper/BulletinPostMapper.java
  backend/src/main/java/com/mybuddy/bulletin_post/repository/BulletinPostCustomRepository.java
  backend/src/main/java/com/mybuddy/bulletin_post/repository/BulletinPostCustomRepositoryImpl.java
  backend/src/main/java/com/mybuddy/bulletin_post/repository/BulletinPostRepository.java
  backend/src/main/java/com/mybuddy/bulletin_post/service/BulletinPostService.java
  backend/src/main/java/com/mybuddy/like/dto/LikeResponseDto.java
  backend/src/main/java/com/mybuddy/like/mapper/LikeMapper.java
  backend/src/main/java/com/mybuddy/like/service/LikeService.java
  backend/src/main/java/com/mybuddy/search/controller/SearchController.java
  backend/src/main/java/com/mybuddy/search/dto/SearchMemberResponseDto.java
  backend/src/main/java/com/mybuddy/search/mapper/SearchMapper.java
  backend/src/main/java/com/mybuddy/search/repository/SearchRepository.java
  backend/src/main/java/com/mybuddy/search/service/SearchService.java
Labels: 개발

#122 [추가/수정] 인터셉터를 이용한 로그인 유저 처리, Exception code 정리 (2023.03.20 강지은)
  backend/src/main/java/com/mybuddy/amenity/service/AmenityService.java
  backend/src/main/java/com/mybuddy/comment/controller/CommentController.java
  backend/src/main/java/com/mybuddy/comment/service/CommentService.java
  backend/src/main/java/com/mybuddy/global/config/InterceptorConfig.java
  backend/src/main/java/com/mybuddy/global/exception/LogicExceptionCode.java
  backend/src/main/java/com/mybuddy/global/interceptor/LoginUserInterceptor.java
  backend/src/test/java/com/mybuddy/comment/controller/CommentControllerTest.java
Labels: 개발

#129 [수정] 권한부여, 리팩토링, getLoginUserId 관련 추가 수정 (2023.03.21 정다운)
  backend/src/main/java/com/mybuddy/bulletin_post/controller/BulletinPostController.java
  backend/src/main/java/com/mybuddy/bulletin_post/dto/BulletinPostDto.java
  backend/src/main/java/com/mybuddy/bulletin_post/mapper/BulletinPostMapper.java
  backend/src/main/java/com/mybuddy/bulletin_post/repository/BulletinPostCustomRepository.java
  backend/src/main/java/com/mybuddy/bulletin_post/repository/BulletinPostCustomRepositoryImpl.java
  backend/src/main/java/com/mybuddy/bulletin_post/service/BulletinPostService.java
  backend/src/main/java/com/mybuddy/global/auth/config/SecurityConfiguration.java
  backend/src/main/java/com/mybuddy/global/exception/LogicExceptionCode.java
  backend/src/main/java/com/mybuddy/global/interceptor/LoginUserInterceptor.java
  backend/src/main/java/com/mybuddy/global/service/CompositeService.java
  backend/src/main/java/com/mybuddy/like/repository/LikeCustomRepository.java
  backend/src/main/java/com/mybuddy/like/repository/LikeCustomRepositoryImpl.java
  backend/src/main/java/com/mybuddy/like/service/LikeService.java
  backend/src/main/java/com/mybuddy/search/controller/SearchController.java
Labels: 개발

#128 [추가] 비밀번호 변경을 위한 이메일 전송 (2023.03.21 강지은)
  backend/src/main/java/com/mybuddy/email/controller/EmailController.java
  backend/src/main/java/com/mybuddy/email/dto/EmailDto.java
  backend/src/main/java/com/mybuddy/email/service/EmailService.java
  backend/src/main/java/com/mybuddy/email/service/EmailServiceImpl.java
Labels: 개발

#135 [수정] 에러 수정 (2023.03.22 정다운)
  backend/src/main/java/com/mybuddy/bulletin_post/controller/BulletinPostController.java
  backend/src/main/java/com/mybuddy/bulletin_post/mapper/BulletinPostMapper.java
  backend/src/main/java/com/mybuddy/bulletin_post/repository/BulletinPostCustomRepositoryImpl.java
  backend/src/main/java/com/mybuddy/global/advice/GlobalExceptionAdvice.java
  backend/src/main/java/com/mybuddy/global/exception/LogicExceptionCode.java
  backend/src/main/java/com/mybuddy/global/interceptor/LoginUserInterceptor.java
  backend/src/main/java/com/mybuddy/global/service/CompositeService.java
  backend/src/main/resources/banner.txt
Labels: 개발

#132 [추가/수정] 게시글 생성 구현, 카카오 맵 검색리스트 창 추가 (2023.03.21 정정수)
  frontend/src/Pages/PostNewPage.jsx
  frontend/src/assets/icons/icon-search.svg
  frontend/src/components/PostNew/PostNewMap.jsx
  frontend/src/components/PostNew/PostNewPlaceHeader.jsx
  frontend/src/components/PostNew/PostNewPlaceList.jsx
  frontend/src/components/PostNew/PostNewPlaceSearch.jsx
  frontend/src/components/PostNew/PostNewlnfo.jsx
  frontend/src/components/PostNew/index.jsx
  frontend/src/components/UI/ImageUploadButton.jsx
  frontend/src/components/UI/Modal/ModalNonContent.jsx
  frontend/src/hooks/useMap.js
  frontend/src/styles/shared.jsx
Labels: 개발

#137 [수정] 회원 검색 에러 응답 수정 (2023.03.22 정다운)
  backend/src/main/java/com/mybuddy/global/exception/LogicExceptionCode.java
  backend/src/main/java/com/mybuddy/search/service/SearchService.java
Labels: 개발

#138 [수정] banner 파일 수정 (2023.03.22 정다운)
  backend/src/main/resources/banner.txt
Labels: 개발

#136 [추가, 수정] 지도 관련 페이지들 추가, 수정 (2023.03.22 왕지호)
  .DS_Store
  frontend/src/Pages/PlacePage.jsx
  frontend/src/assets/marker.svg
  frontend/src/assets/memo_image.svg
  frontend/src/components/KakaoMap/KakaoMap.jsx
  frontend/src/components/KakaoMap/LocationMap.jsx
  frontend/src/components/KakaoMap/LocationModal.jsx
  frontend/src/components/Place/LocationDummy.js
  frontend/src/components/Place/location.json
  frontend/src/components/UI/Dropdown/DropdownLocation.jsx
Labels: 개발

#144 [버그] 무한스크롤 버그 수정 (2023.03.22 정정수)
  frontend/src/Pages/HomePage.jsx
  frontend/src/components/Feeds/FeedList.jsx
  frontend/src/components/FriendSearch/FriendSearchList.jsx
  frontend/src/components/UI/PostItem/index.jsx
  frontend/src/components/UI/PostProfileItem/index.jsx
  frontend/src/hooks/useObserverFetch.js
Labels: 버그

#156 [추가, 수정] 게시글 등록 기능 구현, proxy 미들웨어 추가
  frontend/package.json
  frontend/src/Pages/PostNewPage.jsx
  frontend/src/api/bulletinPostsApi.js
  frontend/src/api/searchApi.js
  frontend/src/components/Feeds/FeedList.jsx
  frontend/src/components/FriendSearch/FriendSearchList.jsx
  frontend/src/components/PostDetail/PostDetailHeader.jsx
  frontend/src/components/PostNew/PostNewMap.jsx
  frontend/src/components/PostNew/PostNewlnfo.jsx
  frontend/src/components/PostNew/index.jsx
  frontend/src/components/UI/ImageUploadButton.jsx
  frontend/src/components/UI/Modal/ModalBase.jsx
  frontend/src/components/UI/Modal/ModalProvider.jsx
  frontend/src/context/ModalContext.jsx
  frontend/src/hooks/useDebounce.js
  frontend/src/hooks/useInput.js
  frontend/src/hooks/useModal.js
  frontend/src/index.js
  frontend/src/setupProxy.js
  frontend/src/utils/api/index.js
  frontend/yarn.lock
Labels: 개발

#159 [수정/추가] 이메일 전송시 URL+토큰, 비밀번호 재설정 (2023.03.24 강지은)
  backend/src/main/java/com/mybuddy/email/controller/EmailController.java
  backend/src/main/java/com/mybuddy/email/service/EmailService.java
  backend/src/main/java/com/mybuddy/email/service/EmailServiceImpl.java
  backend/src/main/java/com/mybuddy/global/auth/config/SecurityConfiguration.java
  backend/src/main/java/com/mybuddy/global/auth/filter/JwtVerificationFilter.java
  backend/src/main/java/com/mybuddy/global/auth/jwt/JwtTokenizer.java
  backend/src/main/java/com/mybuddy/global/config/InterceptorConfig.java
  backend/src/main/java/com/mybuddy/global/interceptor/LoginUserInterceptor.java
  backend/src/main/java/com/mybuddy/member/controller/PasswordController.java
  backend/src/main/java/com/mybuddy/member/dto/MemberPrivacyDto.java
  backend/src/main/java/com/mybuddy/member/service/MemberService.java
  backend/src/main/java/com/mybuddy/member/service/MemberServiceImpl.java
Labels: 개발

#161 [추가/수정] S3업로드 코드 추가, 관련 수정 (2023.03.24 정다운)
  backend/build.gradle
  backend/src/main/java/com/mybuddy/bulletin_post/service/BulletinPostService.java
  backend/src/main/java/com/mybuddy/global/config/AwsConfig.java
  backend/src/main/java/com/mybuddy/global/service/CompositeService.java
  backend/src/main/java/com/mybuddy/global/storage/FileSystemStorageService.java
  backend/src/main/java/com/mybuddy/global/storage/S3StorageService.java
  backend/src/main/java/com/mybuddy/global/storage/StorageService.java
  backend/src/main/java/com/mybuddy/member/service/MemberServiceImpl.java
  backend/src/main/resources/application.yml
Labels: 개발

#163 [추가] multipartResolver : MultiPart 용량 설정, 쿠키(Refresh)에 Secure 설정 (2023.03.25 강지은)
  backend/build.gradle
  backend/src/main/java/com/mybuddy/global/auth/config/SecurityConfiguration.java
  backend/src/main/java/com/mybuddy/global/auth/filter/JwtAuthenticationFilter.java
Labels: 개발

#170 [수정] 댓글 응답에 프로필이미지 추가 및 테스트 코드 반영 (2023.03.26 강지은)
  backend/src/main/java/com/mybuddy/bulletin_post/mapper/BulletinPostMapper.java
  backend/src/main/java/com/mybuddy/comment/dto/CommentResponseDto.java
  backend/src/test/java/com/mybuddy/comment/controller/CommentControllerTest.java
Labels: 개발

#171 [추가] 비밀번호 찾기 및 재설정 기능 구현(2023.03.26 정시원)
  frontend/src/Pages/FindPasswordPage.jsx
  frontend/src/Pages/LoginPage.jsx
  frontend/src/Pages/ResetPasswordPage.jsx
  frontend/src/Pages/SignupPage.jsx
  frontend/src/Router.js
  frontend/src/api/authApi.js
  frontend/src/redux/services/auth.service.js
Labels: 개발

#168 [추가] 업로드 파일 확장자 제한, 예외처리, 용량 예외처리 (2023.03.26 정다운)
  backend/src/main/java/com/mybuddy/global/advice/GlobalExceptionAdvice.java
  backend/src/main/java/com/mybuddy/global/auth/config/SecurityConfiguration.java
  backend/src/main/java/com/mybuddy/global/storage/S3StorageService.java
Labels: 개발

#176 [추가] 프론트엔드 s3 배포 설정 추가 ( 2023.03.27 정정수)
  .github/workflows/client.yml
Labels: 배포

#177 [수정] build, install step 변경 (2023.03.27 정정수)
  .github/workflows/client.yml
Labels: 배포

#173 [수정] Header, follow modal, memberId 적용, 수정 (2023.03.26 왕지호)
  frontend/src/Pages/LoginPage.jsx
  frontend/src/Pages/SignupPage.jsx
  frontend/src/Pages/UserPage.jsx
  frontend/src/components/Follow/FollowModal.jsx
  frontend/src/components/Layout/Header.jsx
Labels: 개발

#178 [수정] yarn build에서 npm build로 수정 (2023.03 27 정정수)
  .github/workflows/client.yml
Labels: 배포

#180 [수정] no-console, no-alert 예외처리 추가 (2023.03.27 정정수)
  frontend/.eslintrc.js
Labels: 배포

#174 [수정/추가] 게시글 상세 기능 구현, 무한스크롤 suspense 옵션 삭제 (2023.03.26 정정수)
  frontend/src/Pages/FriendSearchPage.jsx
  frontend/src/Pages/HomePage.jsx
  frontend/src/Pages/PostDetailPage.jsx
  frontend/src/Pages/PostNewPage.jsx
  frontend/src/api/api.js
  frontend/src/api/bulletinPostsApi.js
  frontend/src/api/commentsApi.js
  frontend/src/api/searchApi.js
  frontend/src/assets/icons/icon-heart.svg
  frontend/src/components/Comments/CommentsCount.jsx
  frontend/src/components/Comments/CommentsForm.jsx
  frontend/src/components/Comments/CommentsItem.jsx
  frontend/src/components/Comments/index.jsx
  frontend/src/components/Feeds/FeedList.jsx
  frontend/src/components/FriendSearch/FriendSearchList.jsx
  frontend/src/components/Layout/Header.jsx
  frontend/src/components/PostDetail/PostDetailHeart.jsx
  frontend/src/components/PostDetail/PostDetailLocation.jsx
  frontend/src/components/PostDetail/PostDetailnfo.jsx
  frontend/src/components/PostDetail/index.jsx
  frontend/src/hooks/bulletinPosts/useCreateBulletinPost.js
  frontend/src/hooks/bulletinPosts/useGetBulletinPost.js
  frontend/src/hooks/bulletinPostsLike/useCreateBulletinPostLike.js
  frontend/src/hooks/bulletinPostsLike/useDeleteBulletinPostLike.js
  frontend/src/hooks/comments/useCreateComments.js
Labels: 개발

#181 [수정] 테스트를 위해 Frontend 배포기준 브랜치 임시 수정 ( 2023.03.27 정정수)
  .github/workflows/client.yml
Labels: 배포

#186 [추가, 수정] 게시글 수정, 삭제 기능 추가 (2023.03.27 정정수)
  frontend/src/Pages/FriendSearchPage.jsx
  frontend/src/api/commentsApi.js
  frontend/src/components/Comments/CommentsItem.jsx
  frontend/src/components/Comments/CommentsList.jsx
  frontend/src/components/Comments/index.jsx
  frontend/src/components/FriendSearch/FriendSearchHeader.jsx
  frontend/src/components/FriendSearch/FriendSearchList.jsx
  frontend/src/components/UI/EditAndRemoveButton/index.jsx
  frontend/src/hooks/comments/useDeleteComments.js
  frontend/src/hooks/comments/useUpdateComments.js
Labels: 개발

#189 [추가/수정] user 정보 받기 추가, 버튼 hover color 추가 (2023.03.27 정정수)
  frontend/src/Pages/PostNewPage.jsx
  frontend/src/api/userApi.js
  frontend/src/components/PostDetail/PostDetailHeader.jsx
  frontend/src/hooks/members/useGetMembersInfo.js
Labels: 개발

#202 [추가] bulletinPost 피드 응답에 createdAt 필드 추가 (2023.03.28 정다운)
  backend/src/main/java/com/mybuddy/bulletin_post/dto/BulletinPostDto.java
  backend/src/main/java/com/mybuddy/bulletin_post/mapper/BulletinPostMapper.java
Labels: 개발

#206 [추가, 수정] 팔로우 / 지도 클릭 이벤트 / amenity page path / 회원정보 수정 관련 페이지들 / Info page 추가, 수정 (2023.03.28.왕지호)
  frontend/src/Pages/InfoPage.jsx
  frontend/src/Pages/UserAboutmePage.jsx
  frontend/src/Pages/UserEditPage.jsx
  frontend/src/Pages/UserFeedPage.jsx
  frontend/src/Pages/UserPlacePage.jsx
  frontend/src/assets/Info/dog2.svg
  frontend/src/assets/Info/dog3.svg
  frontend/src/assets/Info/dog4.svg
  frontend/src/components/Follow/FollowModal.jsx
  frontend/src/components/Follow/FollowerModal.jsx
  frontend/src/components/Info/ColorCard.jsx
  frontend/src/components/Info/ColorLargeCard.jsx
  frontend/src/components/Info/FeedInfoCard.jsx
  frontend/src/components/Info/InfoCard.jsx
  frontend/src/components/Info/MyBuddyInfoCard.jsx
  frontend/src/components/Info/PlaceCard.jsx
  frontend/src/components/KakaoMap/LocationMap.jsx
  frontend/src/components/Layout/Header.jsx
  frontend/src/components/Place/PlaceHeader.jsx
  frontend/src/components/UI/Input.jsx
  frontend/src/components/User/ImageUpload.jsx
  frontend/src/components/User/UserEditContent.jsx
  frontend/src/components/User/UserProfileImg.jsx
Labels: 버그, 개발

#205 [수정] 모달 버튼 통일, 애니메션 닫기 조건부로 수정 (2023.03.29 정정수)
  frontend/src/Pages/PostNewPage.jsx
  frontend/src/components/Comments/CommentsForm.jsx
  frontend/src/components/Comments/index.jsx
  frontend/src/components/PostDetail/PostDetailHeart.jsx
  frontend/src/components/PostDetail/index.jsx
  frontend/src/components/PostEdit/index.jsx
  frontend/src/components/UI/Modal/ModalBase.jsx
  frontend/src/hooks/useAxiosErrorModal.js
Labels: 개발

#209 [버그] 친구찾기 이미지 출력 버그 수정 (2023.03.29 정정수)
  frontend/src/Pages/FriendSearchPage.jsx
  frontend/src/components/UI/PostProfileItem/index.jsx
Labels: 버그

#214 [버그] 게시글 수정 이미지 인식 오류, 기본값 null 지정
  frontend/src/components/PostEdit/index.jsx
  frontend/src/components/UI/Modal/ModalBase.jsx
Labels: 버그

#216 [수정] 마커 이미지 수정, 친구 찾기 검색 옵션 수정
  frontend/src/components/FriendSearch/FriendSearchHeader.jsx
  frontend/src/hooks/useMap.js
Labels: 개발

#218 [추가] 프로파일 기본 이미지 지정 (2023.03.29 정정수)
  frontend/src/components/PostDetail/PostDetailnfo.jsx
  frontend/src/components/PostEdit/PostEditlnfo.jsx
  frontend/src/components/UI/PostProfileItem/index.jsx
  frontend/src/components/UI/UserProfile/index.jsx
  frontend/src/hooks/useImageError.js
Labels: 개발

#220 [수정] info 관련 페이지들 수정 (2023.03.29 왕지호)
  frontend/src/Pages/InfoPage.jsx
  frontend/src/Router.js
  frontend/src/components/Info/ColorCard.jsx
  frontend/src/components/Info/ColorLargeCard.jsx
  frontend/src/components/Info/InfoCard.jsx
  frontend/src/components/Info/MyBuddyInfoCard.jsx
  frontend/src/components/Layout/Header.jsx
Labels: 개발

#221 [수정] 친구찾기 헤더 문구 수정, 게시글 피드 토큰 전송 추가 (2023.03.29 정정수)
  frontend/src/api/bulletinPostsApi.js
  frontend/src/components/Feeds/FeedList.jsx
  frontend/src/components/FriendSearch/FriendSearchHeader.jsx
Labels: 개발

#223 [수정] 배포 환경에 맞춰 9시간 시차 적용 (2023.03.29 정정수)
  frontend/src/utils/time.js
Labels: 개발

#224 [수정] bulletinPost create 에서 amenity 버그 수정 (2023.03.29 정다운)
  backend/src/main/java/com/mybuddy/amenity/entity/Amenity.java
  backend/src/main/java/com/mybuddy/bulletin_post/dto/BulletinPostDto.java
  backend/src/main/java/com/mybuddy/bulletin_post/entity/BulletinPost.java
  backend/src/main/java/com/mybuddy/bulletin_post/mapper/BulletinPostMapper.java
  backend/src/main/java/com/mybuddy/bulletin_post/service/BulletinPostService.java
  backend/src/main/java/com/mybuddy/global/service/CompositeService.java
Labels: 버그

#231 [버그] 프로필 이미지 초기값으로 설정 (2023.03.30 정정수)
  frontend/src/hooks/useImageError.js
Labels: 개발

#232 [수정] 게시글 삭제시 리프레시, 프로필 이름 클릭시 친구페이지 이동 (2023.03.30 정정수)
  frontend/src/components/PostDetail/PostDetailnfo.jsx
  frontend/src/components/PostDetail/index.jsx
  frontend/src/utils/time.js
Labels: 개발

#233 [버그] 게시글 좋아요 클릭 버그 수정 (2023.03.31 정정수)
  frontend/src/components/PostDetail/PostDetailHeart.jsx
  frontend/src/data/FEED_DETAIL_DUMY.js
  frontend/src/mocks/browser.js
  frontend/src/mocks/handlers.js
  frontend/src/mocks/resolvers/member.resolvers.js
  frontend/src/mocks/resolvers/posts.resolvers.js
Labels: 버그

#234 [수정/리팩토링] 비회원 로고 클릭시 info페이지로 이동하도록 수정(2023.03.31 정시원)
  frontend/src/components/Comments/CommentsCount.jsx
  frontend/src/components/Comments/CommentsList.jsx
  frontend/src/components/Layout/Header.jsx
  frontend/src/components/UI/Modal/ModalBase.jsx
Labels: 개발

#237 [배포] 프론트엔드 운영 배포
  frontend/src/Pages/PostNewPage.jsx
  frontend/src/components/Comments/CommentsCount.jsx
  frontend/src/components/Comments/CommentsList.jsx
  frontend/src/components/Layout/Header.jsx
  frontend/src/components/PostDetail/PostDetailHeart.jsx
  frontend/src/components/UI/Modal/ModalBase.jsx
  frontend/src/data/FEED_DETAIL_DUMY.js
  frontend/src/mocks/browser.js
  frontend/src/mocks/handlers.js
  frontend/src/mocks/resolvers/member.resolvers.js
  frontend/src/mocks/resolvers/posts.resolvers.js
Labels: 배포

#238 [수정] 게시글 등록 지도 리팩토링 (2023.03.31 정정수)
  frontend/src/App.js
  frontend/src/Pages/PostNewPage.jsx
  frontend/src/components/PostNew/PostNewMap.jsx
  frontend/src/components/PostNew/PostNewPlaceList.jsx
  frontend/src/components/UI/Modal/ModalBase.jsx
  frontend/src/hooks/useMap.js
Labels: 개발

#239 [버그] 팔로우 한 유저들의 게시물 피드 순서 버그 해결 (2023.03.31 강지은)
  backend/src/main/java/com/mybuddy/bulletin_post/repository/BulletinPostCustomRepositoryImpl.java
Labels: 버그

#243 [배포] 게시글 등록 지도 리팩토링, 지역 기본값 null 지정
  backend/src/main/java/com/mybuddy/bulletin_post/repository/BulletinPostCustomRepositoryImpl.java
  frontend/src/App.js
  frontend/src/Pages/PostNewPage.jsx
  frontend/src/components/PostNew/PostNewMap.jsx
  frontend/src/components/PostNew/PostNewPlaceList.jsx
  frontend/src/components/UI/Modal/ModalBase.jsx
  frontend/src/hooks/useMap.js
Labels: 배포

#244 [버그, 수정] infopage githublink 추가, 지도 페이지 버그/텍스트 수정, 이미지 변경 확장자 jpeg 추가, 게시글 크기 조정, 팔로우 버그 수정 (2023.03.31 왕지호)
  frontend/src/Pages/PlacePage.jsx
  frontend/src/Pages/PostDetailPage.jsx
  frontend/src/Pages/PostEditPage.jsx
  frontend/src/Pages/PostNewPage.jsx
  frontend/src/Pages/UserAboutmePage.jsx
  frontend/src/components/Info/InfoCard.jsx
  frontend/src/components/KakaoMap/LocationMap.jsx
  frontend/src/components/KakaoMap/SearchModal.jsx
  frontend/src/components/User/ImageUpload.jsx
Labels: 버그, 개발
