Repository codestates-seb/seb42_main_011, pull requests merged in 2023-04, with the labels that each got.

#245 [수정] 댓글 프로필 기본이미지 추가, alt 변경 (2023.04.01 정정수)
  frontend/src/components/Comments/CommentsItem.jsx
  frontend/src/components/PostDetail/PostDetailnfo.jsx
  frontend/src/components/PostEdit/PostEditlnfo.jsx
  frontend/src/components/UI/UserProfile/index.jsx
Labels: 개발

#247 [버그/수정] 하단 그림자 짤림현상 해결, 미디어 쿼리 수정 (2023.04.01 정정수)
  frontend/src/components/Feeds/FeedList.jsx
  frontend/src/components/Feeds/PlaceFeedList.jsx
  frontend/src/components/UI/PostItem/index.jsx
  frontend/src/components/UI/PostList/index.jsx
Labels: 버그, 개발

#248 [배포] 프론트엔드 수정 사항 배포
  backend/src/main/java/com/mybuddy/global/service/CompositeService.java
  backend/src/main/java/com/mybuddy/global/storage/S3StorageService.java
  backend/src/main/java/com/mybuddy/member/repository/MemberCustomRepository.java
  backend/src/main/java/com/mybuddy/member/repository/MemberCustomRepositoryImpl.java
  backend/src/main/java/com/mybuddy/member/service/MemberService.java
  backend/src/main/java/com/mybuddy/member/service/MemberServiceImpl.java
  backend/src/main/java/com/mybuddy/search/controller/SearchController.java
  frontend/src/Pages/PlacePage.jsx
  frontend/src/Pages/PostDetailPage.jsx
  frontend/src/Pages/PostEditPage.jsx
  frontend/src/Pages/PostNewPage.jsx
  frontend/src/Pages/UserAboutmePage.jsx
  frontend/src/components/Comments/CommentsItem.jsx
  frontend/src/components/Feeds/FeedList.jsx
  frontend/src/components/Feeds/PlaceFeedList.jsx
  frontend/src/components/Info/InfoCard.jsx
  frontend/src/components/KakaoMap/LocationMap.jsx
  frontend/src/components/KakaoMap/SearchModal.jsx
  frontend/src/components/PostDetail/PostDetailnfo.jsx
  frontend/src/components/PostEdit/PostEditlnfo.jsx
  frontend/src/components/UI/PostItem/index.jsx
  frontend/src/components/UI/PostList/index.jsx
  frontend/src/components/UI/UserProfile/index.jsx
  frontend/src/components/User/ImageUpload.jsx
Labels: 배포

#251 [버그] 홈(피드) 이미지 하단 빈공간 제거, 높이 수정 (2023.04.01 정정수)
  frontend/src/components/UI/PostItem/index.jsx
  frontend/src/components/UI/PostList/index.jsx
Labels: 버그

#253 [버그] 마이페이지, 유저 페이지 관련 페이지들 높이 잘리는 문제 수정 (2023.04.01 왕지호)
  frontend/src/Pages/UserAboutmePage.jsx
  frontend/src/Pages/UserEditPage.jsx
  frontend/src/Pages/UserFeedPage.jsx
  frontend/src/Pages/UserPage.jsx
  frontend/src/Pages/UserPlacePage.jsx
  frontend/src/components/User/ImageUpload.jsx
  frontend/src/components/User/UserEditContent.jsx
  frontend/src/components/User/UserEditHeader.jsx
  frontend/src/components/User/UserHeader.jsx
  frontend/src/components/User/UserInfoComponent.jsx
  frontend/src/components/User/UserProfileImg.jsx
  frontend/src/components/User/UserTabMenu.jsx
Labels: 버그

#254 [버그/수정] 좋아요, 댓글 권한확인 추가, 게시글 상세 스크롤 추가(2023.04.01 정정수)
  frontend/src/Pages/PostDetailPage.jsx
  frontend/src/Pages/PostEditPage.jsx
  frontend/src/components/Comments/CommentsForm.jsx
  frontend/src/components/Comments/CommentsItem.jsx
  frontend/src/components/Comments/index.jsx
  frontend/src/components/Feeds/index.jsx
  frontend/src/components/PostDetail/PostDetailContent.jsx
  frontend/src/components/PostDetail/PostDetailHeart.jsx
  frontend/src/components/PostDetail/index.jsx
  frontend/src/components/PostNew/PostNewPlaceList.jsx
  frontend/src/components/UI/ImageUploadButton.jsx
  frontend/src/components/UI/LoginRequestModal/index.jsx
  frontend/src/components/UI/Modal/Modal.jsx
  frontend/src/components/UI/Modal/ModalNonContent.jsx
  frontend/src/components/UI/UserName/index.jsx
  frontend/src/hooks/useAxiosErrorModal.js
  frontend/src/styles/shared.jsx
Labels: 버그, 개발

#255 [버그] 유저 페이지 관련 버그 수정 (2023.04.01 왕지호)
  frontend/src/Pages/UserAboutmePage.jsx
  frontend/src/Pages/UserEditPage.jsx
  frontend/src/Pages/UserFeedPage.jsx
  frontend/src/Pages/UserPage.jsx
  frontend/src/Pages/UserPlacePage.jsx
Labels: 버그

#256 [배포] 프론트엔드 수정 사항 배포 (2023.04.01 정정수)
  frontend/src/Pages/FriendSearchPage.jsx
  frontend/src/Pages/InfoPage.jsx
  frontend/src/Pages/PostDetailPage.jsx
  frontend/src/Pages/PostEditPage.jsx
  frontend/src/Pages/UserAboutmePage.jsx
  frontend/src/Pages/UserEditPage.jsx
  frontend/src/Pages/UserFeedPage.jsx
  frontend/src/Pages/UserPage.jsx
  frontend/src/Pages/UserPlacePage.jsx
  frontend/src/components/Comments/CommentsForm.jsx
  frontend/src/components/Comments/CommentsItem.jsx
  frontend/src/components/Comments/index.jsx
  frontend/src/components/Feeds/index.jsx
  frontend/src/components/Follow/FollowModal.jsx
  frontend/src/components/Follow/FollowerModal.jsx
  frontend/src/components/FriendSearch/index.jsx
  frontend/src/components/PostDetail/PostDetailContent.jsx
  frontend/src/components/PostDetail/PostDetailHeart.jsx
  frontend/src/components/PostDetail/index.jsx
  frontend/src/components/PostNew/PostNewPlaceList.jsx
  frontend/src/components/UI/ImageUploadButton.jsx
  frontend/src/components/UI/Loading.jsx
  frontend/src/components/UI/LoginRequestModal/index.jsx
  frontend/src/components/UI/Modal/Modal.jsx
  frontend/src/components/UI/Modal/ModalNonContent.jsx
  frontend/src/components/UI/PostItem/index.jsx
  frontend/src/components/UI/PostList/index.jsx
  frontend/src/components/UI/UserName/index.jsx
  frontend/src/components/User/ImageUpload.jsx
  frontend/src/components/User/UserEditContent.jsx
  frontend/src/components/User/UserEditHeader.jsx
  frontend/src/components/User/UserHeader.jsx
  frontend/src/components/User/UserInfoComponent.jsx
  frontend/src/components/User/UserProfileImg.jsx
  frontend/src/components/User/UserTabMenu.jsx
  frontend/src/hooks/useAxiosErrorModal.js
  frontend/src/styles/shared.jsx
Labels: 배포

#257 [버그] 최신 회원 페이지네이션 (2023.04.01 강지은)
  backend/src/main/java/com/mybuddy/global/auth/config/SecurityConfiguration.java
  backend/src/main/java/com/mybuddy/global/service/CompositeService.java
  backend/src/main/java/com/mybuddy/member/repository/MemberCustomRepository.java
  backend/src/main/java/com/mybuddy/member/repository/MemberCustomRepositoryImpl.java
  backend/src/main/java/com/mybuddy/member/service/MemberServiceImpl.java
Labels: 버그

#261 [수정/버그] 게시글 상세, 수정, 등록 팝업 화면 크기별 scale 적용 (2023.04.02 정정수)
  frontend/src/Pages/AmenityPage.jsx
  frontend/src/Pages/PostDetailPage.jsx
  frontend/src/Pages/PostEditPage.jsx
  frontend/src/Pages/PostNewPage.jsx
  frontend/src/components/Feeds/FeedList.jsx
  frontend/src/components/Feeds/PlaceFeedList.jsx
  frontend/src/components/Feeds/index.jsx
  frontend/src/components/Layout/Header.jsx
  frontend/src/components/PostDetail/PostDetailContent.jsx
  frontend/src/components/PostEdit/PostEditContent.jsx
  frontend/src/components/PostNew/PostNewMap.jsx
  frontend/src/components/PostNew/PostNewlnfo.jsx
  frontend/src/components/UI/PostHeader/index.jsx
  frontend/src/components/UI/PostItem/index.jsx
  frontend/src/styles/shared.jsx
Labels: 버그, 개발

#262 [배포] 게시글 상세, 수정, 등록 팝업 화면 크기별 scale 적용 (2023.04.02 정정수)
  backend/src/main/java/com/mybuddy/global/auth/config/SecurityConfiguration.java
  backend/src/main/java/com/mybuddy/global/service/CompositeService.java
  backend/src/main/java/com/mybuddy/member/repository/MemberCustomRepository.java
  backend/src/main/java/com/mybuddy/member/repository/MemberCustomRepositoryImpl.java
  backend/src/main/java/com/mybuddy/member/service/MemberServiceImpl.java
  frontend/src/Pages/AmenityPage.jsx
  frontend/src/Pages/PostDetailPage.jsx
  frontend/src/Pages/PostEditPage.jsx
  frontend/src/Pages/PostNewPage.jsx
  frontend/src/components/Feeds/FeedList.jsx
  frontend/src/components/Feeds/PlaceFeedList.jsx
  frontend/src/components/Feeds/index.jsx
  frontend/src/components/Layout/Header.jsx
  frontend/src/components/PostDetail/PostDetailContent.jsx
  frontend/src/components/PostEdit/PostEditContent.jsx
  frontend/src/components/PostNew/PostNewMap.jsx
  frontend/src/components/PostNew/PostNewlnfo.jsx
  frontend/src/components/UI/PostHeader/index.jsx
  frontend/src/components/UI/PostItem/index.jsx
  frontend/src/styles/shared.jsx
Labels: 배포

#259 [수정] 게시물 피드 조회시 로그인 유저 게시물까지 조회, admin계정 조회 버그 수정 (2023.04.02 정다운)
  backend/src/main/java/com/mybuddy/bulletin_post/repository/BulletinPostCustomRepository.java
  backend/src/main/java/com/mybuddy/bulletin_post/repository/BulletinPostCustomRepositoryImpl.java
  backend/src/main/java/com/mybuddy/bulletin_post/service/BulletinPostService.java
  backend/src/main/java/com/mybuddy/search/mapper/SearchMapper.java
  backend/src/main/java/com/mybuddy/search/repository/SearchCustomRepository.java
  backend/src/main/java/com/mybuddy/search/repository/SearchCustomRepositoryImpl.java
  backend/src/main/java/com/mybuddy/search/repository/SearchRepository.java
  backend/src/main/java/com/mybuddy/search/service/SearchService.java
Labels: 버그, 개발

#265 [수정/버그] 홈(Feed) 로딩 중 텍스트 출력 추가, 팔로우 버그 수정 (2023.04.02 정정수)
  frontend/src/Pages/UserAboutmePage.jsx
  frontend/src/api/userApi.js
  frontend/src/components/Feeds/FeedList.jsx
  frontend/src/components/PostEdit/index.jsx
  frontend/src/components/UI/Loading.jsx
Labels: 개발

#268 [배포] 프론트엔드 변경사항 배포
  backend/build.gradle
  backend/src/main/java/com/mybuddy/bulletin_post/repository/BulletinPostCustomRepository.java
  backend/src/main/java/com/mybuddy/bulletin_post/repository/BulletinPostCustomRepositoryImpl.java
  backend/src/main/java/com/mybuddy/bulletin_post/service/BulletinPostService.java
  backend/src/main/java/com/mybuddy/member/controller/MemberController.java
  backend/src/main/java/com/mybuddy/member/dto/MemberResponseDto.java
  backend/src/main/java/com/mybuddy/member/mapper/MemberMapper.java
  backend/src/main/java/com/mybuddy/search/mapper/SearchMapper.java
  backend/src/main/java/com/mybuddy/search/repository/SearchCustomRepository.java
  backend/src/main/java/com/mybuddy/search/repository/SearchCustomRepositoryImpl.java
  backend/src/main/java/com/mybuddy/search/repository/SearchRepository.java
  backend/src/main/java/com/mybuddy/search/service/SearchService.java
  backend/src/test/java/com/mybuddy/member/controller/MemberControllerTest.java
  frontend/src/Pages/UserAboutmePage.jsx
  frontend/src/api/userApi.js
  frontend/src/components/Feeds/FeedList.jsx
  frontend/src/components/PostEdit/index.jsx
  frontend/src/components/UI/Loading.jsx
Labels: 배포

#269 [버그, 수정, 추가] 이미지 비율, modal media, userpage, imgae page logo, useredit page 관련 수정/추가 (2023.04.02 왕지호)
  frontend/src/Pages/ImagePage.jsx
  frontend/src/Pages/UserEditPage.jsx
  frontend/src/Pages/UserPage.jsx
  frontend/src/components/UI/Modal/Modal.jsx
  frontend/src/components/User/ImageUpload.jsx
  frontend/src/components/User/UserEditContent.jsx
  frontend/src/components/User/UserHeader.jsx
  frontend/src/components/User/UserInfoComponent.jsx
  frontend/src/components/User/UserProfileImg.jsx
  frontend/src/hooks/useUserInuput.js
  frontend/src/hooks/useUserUpdate.js
Labels: 버그, 개발

#270 [수정/버그] 게시글 위치 정보 null 예외처리 추가 (2023.04.03 정정수)
  frontend/src/components/PostDetail/index.jsx
  frontend/src/components/PostEdit/index.jsx
Labels: 버그, 개발

#271 [배포] 프론트엔드 2023.04.02 수정사항 배포
  frontend/src/Pages/ImagePage.jsx
  frontend/src/Pages/UserEditPage.jsx
  frontend/src/Pages/UserPage.jsx
  frontend/src/components/PostDetail/index.jsx
  frontend/src/components/PostEdit/index.jsx
  frontend/src/components/UI/Modal/Modal.jsx
  frontend/src/components/User/ImageUpload.jsx
  frontend/src/components/User/UserEditContent.jsx
  frontend/src/components/User/UserHeader.jsx
  frontend/src/components/User/UserInfoComponent.jsx
  frontend/src/components/User/UserProfileImg.jsx
  frontend/src/hooks/useUserInuput.js
  frontend/src/hooks/useUserUpdate.js
Labels: 배포

#263 [수정/리팩토링] 친구찾기 페이지에 기본으로 최신 회원 리스트 나오게 수정(2023.04.02 정시원)
  frontend/src/Pages/FriendSearchPage.jsx
  frontend/src/api/searchDefaultApi.js
  frontend/src/components/FriendSearch/FriendSearchDefault.jsx
Labels: 개발

#272 [버그] 마이페이지 장소 응답에서, 게시물에 장소 없는 경우를 위한 Null 필터링 (2023.04.03 강지은)
  backend/src/main/java/com/mybuddy/member/mapper/MemberMapper.java
Labels: 버그

#273 [수정] 게시글 생성시 게시글 리스트 refresh 추가, 친구 찾기 로딩 추가 (2023.04.03 정정수)
  frontend/src/Pages/FriendSearchPage.jsx
  frontend/src/Pages/PostNewPage.jsx
  frontend/src/components/FriendSearch/FriendSearchDefault.jsx
Labels: 개발

#274 [배포] 프론트엔드 변경사항 배포 (2023.04.03 정정수)
  backend/src/main/java/com/mybuddy/member/mapper/MemberMapper.java
  frontend/src/Pages/FriendSearchPage.jsx
  frontend/src/Pages/PostNewPage.jsx
  frontend/src/api/searchDefaultApi.js
  frontend/src/components/FriendSearch/FriendSearchDefault.jsx
Labels: 배포

#275 [버그] 누락된 onClick 이벤트 추가
  frontend/src/Pages/FriendSearchPage.jsx
  frontend/src/components/FriendSearch/FriendSearchDefault.jsx
Labels: 버그

#276 [배포] 최신 친구 onClick 이벤트 추가 (2023.04.03 정정수)
  frontend/src/Pages/FriendSearchPage.jsx
  frontend/src/components/FriendSearch/FriendSearchDefault.jsx
Labels: 배포

#277 [수정] 불필요 로그 삭제, 마이페이지 aspect-ratio 추가 (2023.04.03 정정수)
  frontend/src/Pages/UserAboutmePage.jsx
  frontend/src/Pages/UserEditPage.jsx
  frontend/src/api/bulletinPostsApi.js
  frontend/src/components/UI/Modal/Modal.jsx
  frontend/src/components/User/UserProfileImg.jsx
Labels: 개발

#278 [배포] 불필요 로그 삭제, 마이페이지 aspect-ratio 추가 (2023.04.03 정정수)
  frontend/src/Pages/UserAboutmePage.jsx
  frontend/src/Pages/UserEditPage.jsx
  frontend/src/api/bulletinPostsApi.js
  frontend/src/components/UI/Modal/Modal.jsx
  frontend/src/components/User/UserProfileImg.jsx
Labels: 배포

#279 [버그] 친구찾기 페이지 좌우 스크롤 삭제
  frontend/src/components/FriendSearch/index.jsx
Labels: 버그

#280 [배포] 친구찾기 페이지 좌우 스크롤 삭제 배포
  frontend/src/components/FriendSearch/index.jsx
Labels: 배포

#281 [버그] 장소 게시글 리스트 헤더, 클릭 이벤트 오류 수정 (2023.04.03 정정수)
  frontend/src/Pages/AmenityPage.jsx
  frontend/src/Pages/FriendSearchPage.jsx
  frontend/src/components/Feeds/PlaceFeedList.jsx
Labels: 버그

#282 [배포] 장소 게시글 리스트 헤더, 클릭 이벤트 오류 수정 배포 (2023.04.03 정정수)
  README.md
  frontend/src/Pages/AmenityPage.jsx
  frontend/src/Pages/FriendSearchPage.jsx
  frontend/src/components/Feeds/PlaceFeedList.jsx
Labels: 배포

#283 [버그] 마이페이지 장소클릭 버그 수정 (2023.04.03 정정수)
  frontend/src/Pages/UserPlacePage.jsx
Labels: 버그

#285 [배포] amenityName query params로 변경 (2023.04.03 정정수)
  frontend/src/Pages/UserPlacePage.jsx
Labels: 배포

#286 [버그] UI상 보이는 탈퇴 유저의 정보 제거 (2023.04.04 강지은)
  backend/src/main/java/com/mybuddy/bulletin_post/mapper/BulletinPostMapper.java
  backend/src/main/java/com/mybuddy/bulletin_post/repository/BulletinPostCustomRepositoryImpl.java
Labels: 버그

#287 [추가] PerformanceAdvice (2023.04.07 강지은)
  backend/src/main/java/com/mybuddy/global/advice/PerformanceAdvice.java
Labels: 개발

#289 [추가] 장소추천시 유효하지 않은, state-region 쌍 입력시 예외처리
  backend/src/main/java/com/mybuddy/global/auth/config/SecurityConfiguration.java
  backend/src/main/java/com/mybuddy/global/validation/filter/AmenityDataValidationFilter.java
  backend/src/main/java/com/mybuddy/global/validation/validator/RegionValidator.java
Labels: 개발
